# Generated by Django 4.2 on 2023-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.PositiveIntegerField(default=0)),
                ('alimento', models.PositiveIntegerField(default=0)),
                ('medicacao', models.PositiveIntegerField(default=0)),
                ('municao', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
    ]
