# Generated by Django 4.2 on 2023-04-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_sobrevivente_infectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='votos_infectado',
            field=models.IntegerField(default=0),
        ),
    ]
